pipeline {
    agent any
    tools { 
        nodejs 'nodejs' 
    }

    parameters {
        // Define a parameter for the branch name
        string(name: 'BRANCH_NAME', defaultValue: 'main', description: 'Branch to build')
    }


    stages {
        stage('Checkout Code') {
            steps {
                git branch: "${params.BRANCH_NAME}", url: 'https://github.com/botezatuemil/file-parse-api.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker build -t btzemil/file-parse-api:latest .'
                    // Stop the existing container if it's running
                    sh 'docker stop file-parse-api || true && docker rm file-parse-api || true'
                    // Run the new Docker container
                    sh 'docker run -d --name file-parse-api -p 80:5000 file-parse-api:latest'
                }
            }
        }
    }
}